#!/usr/bin/python3

from setuptools import archive_util

import argparse
import glob
import os
import pip
import shutil
import sys
import tempfile

def run_setup(setup, *args):
    import os.path
    import runpy
    import sys

    dirname = os.path.dirname(setup)
    filename = os.path.basename(setup)
    if filename.endswith('.py'):
        filename = filename[:-3]
    sys.path.insert(0, dirname)
    sys.argv[1:] = args
    runpy.run_module(filename, run_name='__main__', alter_sys=True)

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('package', 
        help='a PyPI package spec')
    parser.add_argument('-d', '--destdir', default=os.getcwd(),
                   help='destination directory for srpm (default is current dir)')
    args = parser.parse_args()

    temp = tempfile.mkdtemp(prefix='pypi2fedora.')
    tempdir = {}

    try:
        for d in ['source', 'target']:
            tempdir[d] = os.path.join(temp, d)
            os.mkdir(tempdir[d])
        pip.main(['install', '--disable-pip-version-check', '--no-deps', '--download',
                  tempdir['source'], args.package])

        try:
            package_sources = glob.glob(os.path.join(tempdir['source'], '*'))[0]
        except IndexError:
            print("Package source not found.")
            raise SystemExit(2)

        archive_util.unpack_archive(package_sources, tempdir['target'])

        try:
            setup_py = glob.glob(os.path.join(tempdir['target'], '*', 'setup.py'))[0]
        except IndexError:
            print("setup.py not found; maybe this is not a source archive.")
            raise SystemExit(3)

        os.chdir(os.path.dirname(setup_py))
        run_setup(setup_py, '--command-packages', 'pypi2fedora', 'bdist_fedora', '--source', '--quiet',
                               '--dist-dir', args.destdir)

    finally:
        shutil.rmtree(temp)
